log_dir            = "/databend/metalogs"
metric_api_address = "0.0.0.0:28100"
admin_api_address  = "0.0.0.0:28101"
grpc_api_address   = "0.0.0.0:9191"

[raft_config]
id            = %%NODE%%
raft_dir      = "/databend/raft"
raft_api_port = 28203

raft_listen_host = "0.0.0.0"
raft_advertise_host = "jepsen-n%%NODE%%"

# Start up mode: single node cluster
single        = true